### ISSUE TITLE
Ideia parecidas

### ISSUE THREAD

**Issue by giovannism20** [trabalhando/ondetrabalhar#15]
O criador tem basicamente a mesma ideia porém, voltado para o front-end:

https://github.com/front-jobs/front-jobs.github.io

**Comment by klarkc** [comment]
Acho que a proposta dele é diferente, está mais para um site de vagas de emprego. Aqui queremos apenas listar locais (lojas, praças e etc) bons para se trabalhar e não anunciar vagas de emprego ou profissionais disponíveis.

**Comment by giovannism20** [comment]
Então pelo que eu li até agora do projeto, não peguei então, achei que vocês tinham como objetivo ter um site para mostrar vagas de empregos e não mostrar locais, locais acho que muitas pessoas sabem o problema é se tem vaga nesse tal local.

**Comment by luisfmsouza** [comment]
Acho que vale uma explicação um pouco maior, vamos lá:

Um tempo atrás no Fórum do Front-end BR eu abri [essa issue](https://github.com/frontendbr/forum/issues/241). Acho que título dela diz tudo: Locais de trabalho para Dev Nômade.

Depois de discutir na issue, nós decidimos criar uma ferramenta pra listar bons lugares para se trabalhar. Talvez ai esteja a confusão! A nossa definição do repositório por si só ficou ambigua.

O nosso objetivo é listar bons espaços para desenvolvedores remotos trabalharem. Geralmente esses espaços são cafés ou coworkings, com boa internet e ambiente confortável.

Fez mais sentido agora @GiovanniSM20 ? Sua ajuda continua sendo bem vinda. ;)
