### ISSUE TITLE
Grupo do Slack

### ISSUE THREAD

**Issue by dleitee** [trabalhando/ondetrabalhar#8]
Pessoal, 

Caso queiram participar do grupo no **slack**, favor informar o email nesta issue.

Valeu.

**Comment by klarkc** [comment]
N tem uma URL pra dar join? Melhor que tornar os emails públicos aqui :V

**Comment by dleitee** [comment]
Acabei de criar a url: [https://onde-trabalhar.herokuapp.com/](https://onde-trabalhar.herokuapp.com/)
